image: atlassian/default-image:3

pipelines:
  custom:
    azure:
      - step:
          name: "Build"
          script:
            - nvm install 16.14.0
            - npm install
            - npm run build
            - cd build
            - zip -r ../example-$BITBUCKET_BUILD_NUMBER.zip .
          artifacts: 
            - example-*.zip
      - step:
          name: "Deploy to Azure"
          deployment: Production
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $RESOURCE_GROUP
                AZURE_APP_NAME: $APP_NAME
                ZIP_FILE: 'example-$BITBUCKET_BUILD_NUMBER.zip'
